---
name: CI
on:
  push:
    branches:
      - master
      - 'WIP**'
      - '4.*'
      - 'CURA-*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ultimaker/cura-build-environment
    steps:
    - name: Checkout Cura
      uses: actions/checkout@v2
    - name: Build
      run: docker/build.sh
    - name: Test
      run: docker/test.sh
